import Foundation
import AppKit

public struct ClipboardItem: Identifiable, Codable, Equatable, Sendable {
    public let id: UUID
    public let content: String
    public let timestamp: Date
    public let lineCount: Int
    public let preview: String
    public var isPinned: Bool

    public init(id: UUID = UUID(), content: String, timestamp: Date = Date(), isPinned: Bool = false) {
        self.id = id
        self.content = content
        self.timestamp = timestamp
        self.isPinned = isPinned

        let lines = content.components(separatedBy: .newlines)
        self.lineCount = lines.count

        // Single-line sanitized preview
        let firstLine = lines.first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) ?? ""
        let trimmed = firstLine.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.count > 80 {
            self.preview = String(trimmed.prefix(77)) + "..."
        } else {
            self.preview = trimmed
        }
    }
}

public final class ClipboardManager: @unchecked Sendable {
    public static let shared = ClipboardManager()

    private let lock = NSLock()
    private var items: [ClipboardItem] = []
    private var lastChangeCount: Int
    private var timer: Timer?
    public var maxCapacity: Int = 100
    public let storageURL: URL

    public init(
        maxCapacity: Int = 100,
        storageURL: URL? = nil
    ) {
        self.maxCapacity = maxCapacity
        self.storageURL = storageURL ?? FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".config")
            .appendingPathComponent("titik")
            .appendingPathComponent("clipboard_history.json")
        self.lastChangeCount = NSPasteboard.general.changeCount

        loadHistory()
    }

    public func loadHistory() {
        lock.lock()
        defer { lock.unlock() }

        guard FileManager.default.fileExists(atPath: storageURL.path) else { return }

        do {
            let data = try Data(contentsOf: storageURL)
            let decoder = JSONDecoder()
            let loadedItems = try decoder.decode([ClipboardItem].self, from: data)
            self.items = loadedItems
            Logger.shared.info("Loaded \(loadedItems.count) clipboard items from \(storageURL.path)", subsystem: "Titik.Clipboard")
        } catch {
            Logger.shared.error("Failed to load clipboard history from \(storageURL.path): \(error.localizedDescription)", subsystem: "Titik.Clipboard")
        }
    }

    public func saveHistory() {
        lock.lock()
        defer { lock.unlock() }
        saveHistoryLocked()
    }

    private func saveHistoryLocked() {
        do {
            let dirURL = storageURL.deletingLastPathComponent()
            if !FileManager.default.fileExists(atPath: dirURL.path) {
                try FileManager.default.createDirectory(at: dirURL, withIntermediateDirectories: true)
            }
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            let data = try encoder.encode(items)
            try data.write(to: storageURL, options: .atomic)
            Logger.shared.debug("Saved \(items.count) clipboard items to \(storageURL.path)", subsystem: "Titik.Clipboard")
        } catch {
            Logger.shared.error("Failed to save clipboard history to \(storageURL.path): \(error.localizedDescription)", subsystem: "Titik.Clipboard")
        }
    }

    public func startMonitoring(interval: TimeInterval = 0.5) {
        lock.lock()
        defer { lock.unlock() }

        guard timer == nil else { return }

        // Initial check
        checkPasteboardLocked()

        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        RunLoop.main.add(t, forMode: .common)
        self.timer = t
        Logger.shared.info("Clipboard monitoring started", subsystem: "Titik.Clipboard")
    }

    public func stopMonitoring() {
        lock.lock()
        defer { lock.unlock() }

        timer?.invalidate()
        timer = nil
        Logger.shared.info("Clipboard monitoring stopped", subsystem: "Titik.Clipboard")
    }

    public func checkPasteboard() {
        lock.lock()
        defer { lock.unlock() }
        checkPasteboardLocked()
    }

    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    ]

    private func checkPasteboardLocked() {
        let currentChangeCount = NSPasteboard.general.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        if let types = NSPasteboard.general.types {
            let containsSensitive = types.contains { type in
                Self.sensitiveTypes.contains(type)
            }
            if containsSensitive {
                return
            }
        }

        guard let string = NSPasteboard.general.string(forType: .string) else { return }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        addItemLocked(string)
    }

    public func addItem(_ content: String) {
        lock.lock()
        defer { lock.unlock() }
        addItemLocked(content)
    }

    private func addItemLocked(_ content: String) {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let existingPinned = items.first(where: { $0.content == content })?.isPinned ?? false
        if let existingIdx = items.firstIndex(where: { $0.content == content }) {
            items.remove(at: existingIdx)
        }

        let newItem = ClipboardItem(content: content, isPinned: existingPinned)
        if existingPinned {
            items.insert(newItem, at: 0)
        } else {
            let firstUnpinnedIndex = items.firstIndex(where: { !$0.isPinned }) ?? items.count
            items.insert(newItem, at: firstUnpinnedIndex)
        }

        // Evict if beyond capacity
        if items.count > maxCapacity {
            items = Array(items.prefix(maxCapacity))
        }

        saveHistoryLocked()
        Logger.shared.debug("Added clipboard item: '\(newItem.preview)' (total items: \(items.count))", subsystem: "Titik.Clipboard")
    }

    public func togglePin(id: UUID) {
        lock.lock()
        defer { lock.unlock() }

        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        var item = items.remove(at: index)
        item.isPinned.toggle()

        if item.isPinned {
            items.insert(item, at: 0)
        } else {
            let firstUnpinnedIndex = items.firstIndex(where: { !$0.isPinned }) ?? items.count
            items.insert(item, at: firstUnpinnedIndex)
        }

        saveHistoryLocked()
    }

    public func deleteItem(id: UUID) {
        lock.lock()
        defer { lock.unlock() }

        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items.remove(at: index)
        saveHistoryLocked()
    }

    public func getItems() -> [ClipboardItem] {
        lock.lock()
        defer { lock.unlock() }
        return items
    }

    public func clear() {
        lock.lock()
        defer { lock.unlock() }
        items.removeAll()
        saveHistoryLocked()
    }

    public func copyToPasteboard(_ content: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(content, forType: .string)
        // Update change count so we don't duplicate on next poll
        lock.lock()
        lastChangeCount = pasteboard.changeCount
        addItemLocked(content)
        lock.unlock()
    }
}
